apiVersion: v2
name: ddns-updater-operator
description: A Kubernetes operator that manages DDNS records for ddns-updater
type: application
version: 0.3.0
appVersion: "0.3.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/fredericrous/ddns-updater-operator
sources:
  - https://github.com/fredericrous/ddns-updater-operator
maintainers:
  - name: fredericrous
    url: https://github.com/fredericrous
keywords:
  - ddns
  - dns
  - operator
  - kubernetes
  - ovh
